/*
 * Copyright 2024-2025 NXP
 * NXP Proprietary. This software is owned or controlled by NXP and may only be used
 * strictly in accordance with the applicable license terms. By expressly accepting such terms or by
 * downloading, installing, activating and/or otherwise using the software, you are agreeing that you
 * have read, and that you agree to comply with and are bound by, such license terms. If you do not
 * agree to be bound by the applicable license terms, then you may not retain, install, activate or
 * otherwise use the software.
 */

/*
 * Note:
 * THIS FILE IS AUTO-GENERATED BY TIME SERIES STUDIO. DO NOT MODIFY!
 */

#ifndef _TIMESERIES_freqModel_H_
#define _TIMESERIES_freqModel_H_

#define CLASSIFICATION_LIB_ID_freqModel "539ff4f"

#define TSS_INPUT_DATA_LEN_freqModel                           (256)
#define TSS_INPUT_DATA_DIM_freqModel                           (1)

#define USE_CLASSIFICATION_freqModel
#define TSS_CLASS_NUMBER_freqModel                             (5)

#ifndef _TSS_STATUS_
#define _TSS_STATUS_
/* Error status returned functions in the Time Series Studio library */
typedef enum
{
    TSS_SUCCESS                 = 0, /* No error */
    TSS_STATE_ERROR             = 1, /* State is incorrect */
    TSS_BOARD_ERROR             = 2, /* Board information is incorrect */
    TSS_MEMORY_ERROR            = 3, /* Memory error caused by the HEAP Overflow */
    TSS_PREDICT_NOT_ENABLED     = 4, /* Predict function is not enabled */
    TSS_LEARNING_ERROR          = 5, /* Errors occurs during the learning process */
    TSS_LEARNING_NOT_ENOUGH     = 6, /* Not enough calls to learning */
    TSS_RECOMMEND_LEARNING_DONE = 7, /* Reached the recommended calls to learning */
    TSS_NOT_READY               = 8, /* Function is not ready but planed to support */
    TSS_LICENSE_ERROR           = 9, /* Invalid license */
    TSS_UNKNOWN_ERROR           = 10, /* Unknown error */
} tss_status;
#endif

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief      Initialize the classification algorithm.
 * @retval     TSS_SUCCESS              - Initialization succeed.
 */
tss_status tss_cls_init_freqModel(void);

/**
 * @brief      Predict the probabilities and class index of the specified data.
 * @param[in]  data_input               - The data input for the prediction.
 * @param[out] probabilities            - The predicted probabilities of all classes
 * @param[out] class_index              - The predicted class index.
 * @retval     TSS_SUCCESS              - Prediction succeed.
 */
tss_status tss_cls_predict_freqModel(const float data_input[], float probabilities[], int *class_index);

#ifdef __cplusplus
}
#endif

#endif /* _TIMESERIES_freqModel_H_ */